
INSERT INTO SYS_DICTIONARY_ITEM (`ID`, `DICT_NAME`, `DICT_TYPE`, `ISEDIT`) VALUES (UUID(), '性别', 'PERSION_SEX', 0);
INSERT INTO SYS_DICTIONARY (`ID`, `DICT_NAME`, `DICT_TYPE`, `DICT_VALUE`, `EXT01`, `EXT02`, `EXT03`, `EXT04`, `EXT05`, `REMARK`) VALUES (UUID(), '男', 'PERSION_SEX', '1', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO SYS_DICTIONARY (`ID`, `DICT_NAME`, `DICT_TYPE`, `DICT_VALUE`, `EXT01`, `EXT02`, `EXT03`, `EXT04`, `EXT05`, `REMARK`) VALUES (UUID(), '女', 'PERSION_SEX', '2', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO SYS_DICTIONARY (`ID`, `DICT_NAME`, `DICT_TYPE`, `DICT_VALUE`, `EXT01`, `EXT02`, `EXT03`, `EXT04`, `EXT05`, `REMARK`) VALUES (UUID(), '保密', 'PERSION_SEX', '3', NULL, NULL, NULL, NULL, NULL, NULL);
